[package]
name = "subdb"
version = "0.1.0"
authors = ["Gav Wood <gavin@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
parity-scale-codec = "1.3.0"
blake2-rfc = "0.2.18"